# Generated by Django 4.2.7 on 2023-11-10 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Libros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('numero_pagina', models.IntegerField()),
                ('editorial', models.CharField(max_length=255)),
                ('ISBN', models.CharField(max_length=13, unique=True)),
            ],
        ),
    ]
