# Generated by Django 4.2.7 on 2023-11-13 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autores', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='escribir',
            old_name='dia_mes_año',
            new_name='dia_mes_ano',
        ),
    ]
